### ISSUE TITLE
How to produce a moho depth image using receiver function

### ISSUE THREAD

**Issue by geophysics91** [paudetseis/RfPy#11]
Hii expert, I have calculated moho depth below each station.Now i want to do a image plot of the moho depth on the basemap,how can it be done can you please suggest.

**Comment by paudetseis** [comment]
Hi @geophysics91 - I am glad that you were able to get Moho depths. Plotting them on a map is a step that is external to the functionalities included with RfPy. I suggest using [cartopy](https://scitools.org.uk/cartopy/docs/latest/) to do this. Check out the examples in the gallery section and do a search on google for "cartopy scatter".
