### ISSUE TITLE
compute the rf for offline station

### ISSUE THREAD

**Issue by datseismo** [paudetseis/RfPy#28]
As a new user to receiver functions,  can you please provide/suggest some code for the computation of the rf  of a offline station from scratch. I have only raw data recorded in a station saved in a directory. How can i compute rf using the same data sets. Moreover I have  stla,stlo,elevation information with me.

**Comment by paudetseis** [comment]
Thanks for your interest in the code. You can consult the documentation, in particular the tutorials (start with `StDb` tutorial to build your station database) here: https://paudetseis.github.io/RfPy/tutorials.html
